name: CI

on: [push, fork, pull_request, workflow_dispatch, workflow_call]

jobs:

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@master

  py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          pip install uv
          uv tool run pdm export --pyproject | uv pip install --system -r -
          yarn global add pyright
      - name: Ruff
        run: |
          ruff format --check --diff
          ruff check --diff
      - name: Pyright
        run: pyright --stats

  js:
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
      fail-fast: false
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pull changes
        run: git pull

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8 # stackblitz supports pnpm v8

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Check
        run: pnpm check

      - uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu'
        with:
          path: pnpm-lock.yaml
          name: lockfile

  lock:
    needs: [typos, py, js]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: lockfile
      - name: Commit lockfile
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add pnpm-lock.yaml -f
          locked_branch_name=$(git branch --show-current)-locked
          git checkout -b $locked_branch_name
          git commit -m 'add `pnpm-lock.yaml`'
          git push --set-upstream origin $locked_branch_name -f

  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Build static site
        run: pnpm install --prod && pnpm build
      - name: Upload pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: build
      - name: Deploy
        uses: actions/deploy-pages@v4
        id: deployment
