name: Auto update

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      updated: ${{ steps.set-output.outputs.updated }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Check updates
        id: taze
        run: pnpx taze -a --failOnOutdated
        continue-on-error: true

      - name: Updates dependencies
        if: steps.taze.outcome == 'failure'
        run: |
          pnpx taze -w
          pnpm update

      - name: Commit changes
        if: steps.taze.outcome == 'failure'
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add package.json
          git commit -m 'update dependencies'
          git push
      - name: Set output
        id: set-output
        if: steps.taze.outcome == 'failure'
        run: |
          echo "updated=true" >> $GITHUB_OUTPUT

  invoke:
    permissions:
      pages: write
      id-token: write
      contents: write
    needs: update
    uses: ./.github/workflows/ci.yml
    if: needs.update.outputs.updated == 'true'
